from pathlib import Path
import json,hashlib
A=Path(__file__).parent;p=json.loads((A/'prewrite.json').read_text())['structuredContent'];slides={s['objectId']:s for s in p['slides']}
subs={'stage4':'Compare crop features with label phrases','stage5':'Primitive scores and crop features feed the Comp MLP','stage6':'Add phrase-composition scores to the Comp MLP','01-mlp':'Crops, RoI and the entire frame; direct 184-label prediction','02-attention':'Let the actor select relevant entire-frame evidence','04-all184-contrastive':'Align visual and adapted text features before language fusion','06-dcb-blend':'Blend two attention experts trained with different objectives','composition':'Stages 5 and 6 share primitive evidence for learned compositions','roi-align':'Sample the actor region from the entire-frame feature map','tail-case':'Large vehicle stopped at a junction: an original-study example'}
items=[]
for m in json.loads((A/'manifest.json').read_text()):
 if not m['slide_id']:continue
 slug=m['slug'];s=slides[m['slide_id']];e=next(e for e in s['pageElements'] if 'image'in e);path=str((A/(slug+'.png')).resolve());requests=[{'replaceImage':{'imageObjectId':e['objectId'],'url':path,'imageReplaceMethod':'CENTER_INSIDE'}},{'updatePageElementAltText':{'objectId':e['objectId'],'title':slug+' diagram','description':f'Editable source: artifacts/defense-score-notation-20260928/{slug}.drawio. Title-free; white probability scorecards, feature tensors preserved, standardized InternVideo2-S encoder labels. Source ancestry: {m["source"]}. PNG SHA256 '+hashlib.sha256(Path(path).read_bytes()).hexdigest()}}]
 candidates=[e for e in s['pageElements'] if e.get('shape',{}).get('placeholder',{}).get('type')=='BODY' and not e.get('shape',{}).get('text',{}).get('textElements')]
 if candidates:
  sub=candidates[0];id=sub['objectId'];size=sub['size'];sx=660*12700/size['width']['magnitude'];sy=28*12700/size['height']['magnitude']
  requests.append({'updatePageElementTransform':{'objectId':id,'applyMode':'ABSOLUTE','transform':{'scaleX':sx,'scaleY':sy,'translateX':81*12700,'translateY':102*12700,'unit':'EMU'}}})
 else:
  id='score_sub_'+slug.replace('-','_');requests.append({'createShape':{'objectId':id,'shapeType':'TEXT_BOX','elementProperties':{'pageObjectId':s['objectId'],'size':{'width':{'magnitude':660,'unit':'PT'},'height':{'magnitude':28,'unit':'PT'}},'transform':{'scaleX':1,'scaleY':1,'translateX':81,'translateY':102,'unit':'PT'}}}})
 requests.extend([{'insertText':{'objectId':id,'text':subs[slug]}},{'deleteParagraphBullets':{'objectId':id,'textRange':{'type':'ALL'}}},{'updateTextStyle':{'objectId':id,'textRange':{'type':'ALL'},'style':{'fontFamily':'Georgia','fontSize':{'magnitude':18,'unit':'PT'},'bold':False,'italic':False,'foregroundColor':{'opaqueColor':{'rgbColor':{'red':.33,'green':.33,'blue':.33}}}},'fields':'fontFamily,fontSize,bold,italic,foregroundColor'}},{'updateParagraphStyle':{'objectId':id,'textRange':{'type':'ALL'},'style':{'spaceAbove':{'magnitude':0,'unit':'PT'},'spaceBelow':{'magnitude':0,'unit':'PT'},'indentStart':{'magnitude':0,'unit':'PT'},'indentEnd':{'magnitude':0,'unit':'PT'},'indentFirstLine':{'magnitude':0,'unit':'PT'},'lineSpacing':100},'fields':'spaceAbove,spaceBelow,indentStart,indentEnd,indentFirstLine,lineSpacing'}}])
 # Keep the checkpoint/probability interpretation in presenter notes, outside diagram labels.
 noteid=s['slideProperties']['notesPage']['notesProperties']['speakerNotesObjectId'];nt=''.join(t.get('textRun',{}).get('content','') for e in s['slideProperties']['notesPage']['pageElements'] if e['objectId']==noteid for t in e.get('shape',{}).get('text',{}).get('textElements',[]))
 add='\n\nDiagram notation: p(y | x) denotes a predicted sigmoid class score given available input evidence; these multilabel scores need not sum to one and are not claimed to be calibrated. c denotes a composition label, d a duplex, t a triplet. Final detector scores s(y) include event-score confidence weighting; agentness and agent outputs remain YOLO-derived. White scorecards distinguish predictions from feature vectors and phrase embeddings. Encoder labels use Brandon’s requested InternVideo2-S Text Encoder / Video Encoder naming; checkpoint identity remains InternVideo2-CLIP-S in source provenance.\n'
 requests.append({'insertText':{'objectId':noteid,'text':add,'insertionIndex':len(nt.rstrip('\n'))}})
 (A/(slug+'-requests.json')).write_text(json.dumps(requests));items.append({'slug':slug,'slide_id':s['objectId'],'image':path,'subtitle_id':id})
(A/'slide-plan.json').write_text(json.dumps(items,indent=2));print(len(items),'slide images and subtitles')
