from pathlib import Path
import json,re
A=Path(__file__).parent;p=json.loads((A/'constructed.json').read_text())['structuredContent'];slides={s['objectId']:s for s in p['slides']};req=[]
notes={
'rev_12':(80,'Stage 4: Semantic Crop Classifier. Frozen crop and text encoders provide features and184 phrase vectors. Project the crop feature and score its similarity to each phrase. Motivation: share semantic information across rare labels. This is phrase scoring, with no Comp MLP. At evaluation YOLO supplies boxes and agent scores. Source: artifacts/defense-stage456-illustrated-20260928/technical-review.md.'),
'rev_13':(80,'Stage 5: Semantic Crop Classifier + Comp MLP. A linear classifier provides49 sigmoid primitive/agentness scores. Concatenate them with1024 crop features; the Comp MLP learns49 duplex and86 triplet scores. Motivation: reuse primitive evidence while learning visual combinations. There is no explicit phrase-score input. The final action/location scores bypass the Comp MLP. Source: technical-evidence.md in artifacts/defense-committee-refinement-20260928/.'),
'comm_composition':(90,'Trace the same bus used in the model diagrams. Its annotated label is Bus-MovAway-OutgoLane. Eight cropped frames produce one crop feature vector. The primitive sigmoid scores and crop features jointly condition135 learned composition scores:49 duplex and86 triplet. Stage6 additionally supplies135 phrase-composition sigmoid scores. These are learned outputs, not a product of primitive probabilities or every possible Cartesian combination. We retain the benchmark composition vocabulary to score its evaluated events. Primitive sharing can support a rare combination, but does not guarantee tail improvement. This is an illustrative GT example, not measured predictions. Stage4 and standalone contextual heads do not have this CompMLP dependency. Full code citations: artifacts/defense-committee-refinement-20260928/technical-evidence.md.'),
'comm_roi_align':(80,'Follow two paths: YOLO proposes the candidate box; the frozen video encoder processes the entire eight-frame clip. Its keyframe spatial map has16×16 locations, each with1024 channels. Map normalized unpadded box coordinates onto that map, keeping fractional locations. RoIAlign uses bilinear interpolation with aligned=True, adaptive sampling and7×7 output bins. Spatial mean pooling gives one1024-D RoI feature vector for the contextual head. RoIAlign samples features; it does not propose boxes. The padded pixel-crop branch is separate. The photo box is illustrative GT and colored feature cells are schematic. Training cache uses GT-positive/random boxes; inference uses YOLO proposals. Source: contextual-roi/extract_features.py and technical-evidence.md in this refinement bundle.'),
'rev_15':(110,'Contextual standalone head: crops, RoI features and the entire frame, with box position. Motivation: a tight crop can omit the surrounding event context. This model predicts184 outputs directly; it does not feed primitive scores to a separate Comp MLP. Compare mean-pooled scene tokens with actor-query attention, then test an all184 contrastive auxiliary on each. The auxiliary aligns pre-language visual features and adapted phrases; gradients update both adapters, while encoders remain frozen. Attention and contrastive architecture close-ups are in the backup slides; the matched results follow. These are hypotheses, not guaranteed gains. Source: artifacts/contextual-evolution-20260924/technical-evidence.md; contextual-roi-all184/model.py.'),
'rev_18':(160,'Motivation: complementary experts may preserve useful predictions that a single head loses. Both attention experts use language and directly predict184 scores. ExpertA has classification loss only; ExpertB adds corrected all184 contrastive alignment. Freeze the experts, keep A’s primitive scores, and blend135 composition scores with one global weight selected by development triplet crop AP. This is not a sample-dependent gate. DCB retrains both experts with FRCB-inspired difficulty-calibrated BCE, retaining this inference path; B still has the contrastive auxiliary. DCB improves overall triplet AP but fails its standalone tail-improvement endpoint. Cosine-weighting both input feature streams, raised by Moradi, is a different architectural alternative and was not this blend. Source: contextual-gate/prepare_blend.py; contextual-roi-dcb/dcb.py; artifacts/contextual-evolution-20260924/technical-evidence.md.'),
'comm_tail_case':(75,'Measured example: ROAD-Waymo validation frame train_00797_00018, original controlled encoders, seed0. Highlighted candidate has IoU0.679 to an annotated large vehicle stopped at a junction. The class has1,895 training boxes, placing it in deep28. For this ground truth, Stage4 ranks288, Stage5 ranks81,918, Stage6 ranks4,708. At the diagnostic top615 class predictions, onlyStage4 recovers it. Stage6 improves overStage5 here, but does not retain Stage4’s recovery. This motivates testing selective fusion; it does not prove semantic causality or that a later model repairs the same case.615 equals the GT count for a post-hoc diagnostic budget, not an operational threshold. GT-match ranks may use different winning boxes; the highlighted YOLO candidate and its IoU illustrate localization. Other simultaneous GT labels exist. Source: artifacts/defense-committee-refinement-20260928/tail-evidence.md and language-fusion-diagnostics/selected-visual-cases.json.'),
'rev_14':(0,'BACKUP: Stage6 Semantic Crop Classifier + Phrase Fusion + Comp MLP. Same primitive-conditioned composition path asStage5, with135 additional phrase-composition scores. Its1208 inputs comprise1024 crop features,49 primitive/agentness sigmoid scores and135 phrase-composition sigmoid scores. CompMLP produces49 duplex+86 triplet scores. Architecture source: artifacts/defense-stage456-illustrated-20260928/stage6.drawio; code citations: artifacts/defense-committee-refinement-20260928/technical-evidence.md.'),
'rev_16':(0,'BACKUP: actor-query scene attention replaces mean pooling to select scene tokens using the actor representation. Crop/RoI/position information and the direct184-output readout remain. No primitive-conditioned CompMLP in this standalone head. Source: contextual-roi/model.py and artifacts/contextual-evolution-20260924/technical-evidence.md.'),
'rev_17':(0,'BACKUP: corrected all184 multi-positive contrastive alignment between normalized pre-language visual RoI and adapted text features. Temperature0.07 and auxiliary weight0.001. Gradients reach visual and text adapters, not the frozen encoders. Not a loss on output scores or the joint RoI. Historical86-only comparison also changed target gradients, so it is not a clean scope ablation. This is distinct from InternVideo2 backbone adaptation on ROAD. Source: contextual-roi-all184/model.py; artifacts/contextual-evolution-20260924/technical-evidence.md.')}
# Existing evidence/results notes retained; targeted clarification only.
for id,(sec,body) in notes.items():
 noteid=slides[id]['slideProperties']['notesPage']['notesProperties']['speakerNotesObjectId'];text=('Backup; outside timed main talk.\n' if sec==0 else f'Rehearsal cue: {sec} seconds.\n')+body+'\n'
 req.extend([{'deleteText':{'objectId':noteid,'textRange':{'type':'ALL'}}},{'insertText':{'objectId':noteid,'text':text}}])
titles={'rev_13':'Stage 5: primitive-conditioned scores','rev_14':'Stage 6: phrase-aided composition','rev_15':'Context: direct 184-score readout'}
for id,t in titles.items():
 e=next(e for e in slides[id]['pageElements'] if e.get('shape',{}).get('placeholder',{}).get('type')=='TITLE')
 req.extend([{'deleteText':{'objectId':e['objectId'],'textRange':{'type':'ALL'}}},{'insertText':{'objectId':e['objectId'],'text':t}}])
# Clear all-label vs composition-specific ambiguity on metric slide.
id='r19_d16_p4_i84';text='184 scores: agentness, primitives, compositions\nStage 5/6: primitive-conditioned composition\nContextual standalone: direct 184-score readout\nRank detections per label; match at IoU ≥ 0.5'
req.extend([{'deleteText':{'objectId':id,'textRange':{'type':'ALL'}}},{'insertText':{'objectId':id,'text':text}},{'createParagraphBullets':{'objectId':id,'textRange':{'type':'ALL'},'bulletPreset':'BULLET_DISC_CIRCLE_SQUARE'}}])
# First eleven slides remain untouched. Preserve all architecture views as optional Q&A detail.
first=[s['objectId'] for s in p['slides'] if s['objectId'].startswith('def_') or s['objectId']=='h65bfaa764efcf51d_1_248']
assert len(first)==11
main=first+['rev_12','rev_13','comm_composition','comm_roi_align','rev_15','rev_18','rev_19','rev_20','rev_21','comm_tail_case','rev_22','rev_23','rev_24','rev_25'];backup=['rev_14','rev_16','rev_17'];order=main+backup
assert len(main)==25 and set(order)==set(slides)
for i,id in enumerate(order[11:],11):req.append({'updateSlidesPosition':{'slideObjectIds':[id],'insertionIndex':i}})
for id in backup:req.append({'updateSlideProperties':{'objectId':id,'slideProperties':{'isSkipped':True},'fields':'isSkipped'}})
# Navigation links in contextual speaker notes are source-independent Google slide URLs.
(A/'finalize-requests.json').write_text(json.dumps(req));(A/'order.json').write_text(json.dumps({'main':main,'backup':backup,'notes':notes,'title_time_allowance_seconds':75},indent=2));print(len(req),p['revisionId'])
