import json,pathlib,hashlib
A=pathlib.Path('/data/repos/wiki/artifacts/defense-stage456-illustrated-20260928');d=json.load(open(A/'before.json'))['structuredContent'];out=[];notes=[]
for n in [4,5,6]:
 s=d['slides'][n+7];assert s['objectId']==f'rev_{n+8}'
 old=next(e for e in s['pageElements'] if 'image'in e)
 cap=next(e for e in s['pageElements'] if 'caption'in e['objectId'])
 path=str(A/f'stage{n}.png');oid=f'illustrated_stage{n}'
 req=[{'deleteObject':{'objectId':old['objectId']}},{'deleteObject':{'objectId':cap['objectId']}},{'createImage':{'objectId':oid,'url':path,'elementProperties':{'pageObjectId':s['objectId'],'size':{'width':{'magnitude':880,'unit':'PT'},'height':{'magnitude':880*1081/2520,'unit':'PT'}},'transform':{'scaleX':1,'scaleY':1,'translateX':40,'translateY':100,'unit':'PT'}}}},{'updatePageElementAltText':{'objectId':oid,'title':f'Stage {n} illustrated architecture','description':f'Editable source: artifacts/defense-stage456-illustrated-20260928/stage{n}.drawio. Architecture ancestor: artifacts/defense-30min/alignment/stage{n}.drawio. Visual ancestor: contextual-evolution-20260924/simplified/01-mlp.drawio. PNG SHA256 {hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()}. Original architecture; illustrative GT bus, not a measured YOLO prediction.'}}]
 noteid=s['slideProperties']['notesPage']['notesProperties']['speakerNotesObjectId']
 nt=''.join(t.get('textRun',{}).get('content','') for e in s['slideProperties']['notesPage']['pageElements'] if e['objectId']==noteid for t in e.get('shape',{}).get('text',{}).get('textElements',[]))
 specific={4:'Stage4: project1024 crop features to512, L2-normalize and compare with normalized frozen184×512 phrases. Learned exp(log_tau) scale and184 biases precede sigmoid. Keep173 action/location/duplex/triplet scores for evaluation. No CompMLP.',5:'Stage5: Linear1024→184 plus sigmoid. The first49 raw primitive probabilities concatenate with1024 crop features, giving1073→512→135 composition MLP. Flat action22/location16 probabilities bypass it. MLP duplex49/triplet86 replace flat composition predictions; they are not averaged with them. No text tower or phrase-score input.',6:'Stage6 preserves every Stage5 path and adds Stage4 calibrated phrase scoring. Only135 raw phrase composition probabilities enter C, along with49 raw flat primitives and1024 crop features:1208→512→135. Phrase scores do not bypass the composition MLP to become final outputs.'}[n]
 nt+='\n\nIllustrated diagram revision, 2026-09-28: '+specific+' Common original frozen-encoder protocol: one fixed 2× padded candidate window over eight frames yields a1024-D target-frame crop vector. Three real photo tiles illustrate eight frames. Original models have no separate full-frame feature branch, RoIAlign branch, box-position embedding, residual adapter, scene attention or language cross-attention. Video-clip photos only illustrate crop construction. Head probabilities are sigmoid values before detector-confidence weighting. Multiply only173 event probabilities by q; YOLO supplies agentness q and hard agent-class q directly, never q². Positive head training uses GT crops; negatives include random/YOLO junk; evaluation uses YOLO candidate boxes. Learned-head flame badges refer to separate head-training steps using cached encoders and opposite-fold predictions, not joint backpropagation. The pictured gold box is illustrative ground truth; no confidence or prediction is asserted. Visual source: contextual-evolution-20260924/simplified/01-mlp.drawio. Editable derivatives/code evidence/provenance: artifacts/defense-stage456-illustrated-20260928/.\n'
 req.extend([{'deleteText':{'objectId':noteid,'textRange':{'type':'ALL'}}},{'insertText':{'objectId':noteid,'text':nt}}]);out.append({'stage':n,'path':path,'requests':req});notes.append({'stage':n,'slide':n+8,'notes':nt})
(A/'slide-requests.json').write_text(json.dumps(out));(A/'notes.json').write_text(json.dumps(notes,indent=2))
